name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mediawiki: [ 'REL1_46', 'master' ]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: sqlite3, pdo_sqlite, gd, intl
          tools: composer

      - name: Setup MediaWiki
        uses: lucaswerkmeister/setup-mediawiki@v1
        id: setup-mediawiki
        with:
          version: ${{ matrix.mediawiki }}

      - name: Checkout TextExtracts
        uses: actions/checkout@v4
        with:
          repository: wikimedia/mediawiki-extensions-TextExtracts
          ref: ${{ matrix.mediawiki }}
          path: ${{ steps.setup-mediawiki.outputs.install-directory }}/extensions/TextExtracts

      - name: Checkout PageImages
        uses: actions/checkout@v4
        with:
          repository: wikimedia/mediawiki-extensions-PageImages
          ref: ${{ matrix.mediawiki }}
          path: ${{ steps.setup-mediawiki.outputs.install-directory }}/extensions/PageImages

      - name: Checkout Extension
        uses: actions/checkout@v4
        with:
          path: ${{ steps.setup-mediawiki.outputs.install-directory }}/extensions/OpenGraph

      - name: Register Extensions
        run: |
          cd -- "${{ steps.setup-mediawiki.outputs.install-directory }}"
          echo "wfLoadExtension( 'TextExtracts' );" >> LocalSettings.php
          echo "wfLoadExtension( 'PageImages' );" >> LocalSettings.php
          echo "wfLoadExtension( 'OpenGraph' );" >> LocalSettings.php
          php maintenance/run.php update --quick

      - name: Run PHPUnit Tests
        run: |
          cd -- "${{ steps.setup-mediawiki.outputs.install-directory }}"
          composer phpunit -- extensions/OpenGraph/tests/phpunit
